/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf 
Author: ely3 (https://sketchfab.com/ely3)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shoe-4a5b805b7cab409b9a0534faa9f4b07b
Title: Shoe
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Left_Shoe_0">
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Left_tex} />
              </group>
              <group name="Right_Shoe_1">
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Right_tex} />
              </group>
              <group name="laces_2">
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Laces_tex} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
